config/routes.rb
Myrottenpotatoes::Application.routes.draw do
    resources :movies
    root :to => redirect('/movies')
    
    get 'auth/:provider/callback' => 'sessions#create'
    post 'logout' => 'sessions#destroy'
    get 'auth/failure' => 'sessions#failure'
    get 'auth/facebook',:as => 'login'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  def self.all_ratings ; %w[G PG PG-13 R NC-17] ; end #  shortcut: array of strings
  validates :title, :presence => true
  validates :release_date, :presence => true
  validate :released_1930_or_later # uses custom validator below
  validates :rating, :inclusion => {:in => ['G','PG','PG-13','R','NC-17']},
    :unless => :grandfathered?
  def released_1930_or_later
    errors.add(:release_date, 'must be 1930 or later') if
      release_date && release_date < Date.parse('1 Jan 1930')
  end
  @@grandfathered_date = Date.parse('1 Nov 1968')
  def grandfathered?
    release_date && release_date < @@grandfathered_date
  end
  
  before_save:capitalize_title
  def capitalize_title
    self.title = self.title.split(/\s+/).map(&:downcase).map(&:capitalize).join('')
  end
      
  
  
end

app/models/moviegoer.rb
class Moviegoer < ApplicationRecord
    def self.create_with_omniauth(auth)
        Moviegoer.create!(
            :provider => auth["provider"],
            :uid => auth["uid"],
            :name => auth["info"]["name"])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  protected # prevents method from being invoked by a route
  def set_current_user
    # we exploit the fact that the below query may return nil
    @current_user ||= Moviegoer.find_by(:id => session[:user_id])
    #redirect_to login_path and return unless @current_user
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        @movies = Movie.all
    end
    
    def show
        id = params[:id]
        @movie = Movie.find(id)
    end
    
    def new
        @movie = Movie.new
    end
    
    def create
        @movie = Movie.new(allowparams)
        if @movie.save
           flash[:notice] = "#{@movie.title} was successfully created."
           redirect_to movie_path (@movie)
        else
            render'new'
        end
    end
    
    def allowparams
        params[:movie].permit(:title,:rating,:release_date)
    end
    
    def edit
        @movie = Movie.find params[:id]
    end
    
    def update
        @movie = Movie.find params[:id]
        if @movie.update_attributes!(allowparams)
           flash[:notice] = "#{@movie.title} was successfully update"
           redirect_to movie_path(@movie)
        else
            render 'edit'
        end
    end
    
    def destroy
        @movie = Movie.find params[:id]
        @movie.destroy
        flash[:notice] = "Movie '#{@movie.title}' delete"
        redirect_to movies_path 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # user shouldn't have to be logged in before logging in!
  skip_before_action :set_current_user
  def create
    auth=request.env["omniauth.auth"]
    user=Moviegoer.find ||
      Moviegoer.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to movies_path
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logged out successfully.'
    redirect_to movies_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RottenPotatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
  -# this goes just inside %body:
  - if flash[:notice]
    #notice.message= flash[:notice]
  - elsif flash[:warning]
    #warning.message= flash[:warning]
  = render :partial=>'log_in'
  =yield
  
  

app/views/movies/_log_in.html.haml
#login
  - if @current_user
    %p.welcome  Welcome, #{@current_user.name}!
    = link_to 'Log Out', logout_path, :method => :post
  - else
    %p.login= link_to 'Log in with your Facebook account', '/auth/facebook'

app/views/movies/_movie_form.html.haml
-# insert at top of _movie_form.html.haml
- unless @movie.errors.empty?
  #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      - @movie.errors.full_messages.each do |error|
        %li= error

= label :movie, :title, 'Title'
= text_field :movie,'title'
= label :movie, :rating, 'Rating'
= select :movie, :rating, ['G','PG','PG-13','R','NC-17']

= label :movie,:release_date,'Released On'
= date_select :movie, :release_date

app/views/movies/edit.html.haml
%h2 Edit Existing  Movie

= form_tag movie_path(@movie), :method => :put do

  = render :partial => 'movie_form'
  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More info
  %tbody
    -@movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}",movie_path(movie)

= link_to 'Add new movie', new_movie_path
    

app/views/movies/new.html.haml
%h2 Create New Movie

= form_tag '/movies', :method => :post do

  = render :partial => 'movie_form'
  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
%h2 Details about #{@movie.title}



%ul#details
  @li
  Rating:
  = @movie.rating
  @li
  Released on:
  = @movie.release_date.strftime("%B %d, %Y")
    
%h3 Description:

%p#description= @movie.description

= link_to 'Edit info', edit_movie_path(@movie)
= link_to 'Delete', movie_path(@movie), :method => :delete
= link_to 'Back to movie list', movies_path